hoophq/hoop

- .env.sample
- .github/workflows/release.yml
- Dockerfile
- agent/controller/terminal.go
- client/cmd/admin/license.go
- scripts/publish-release.sh
- Remove comments and unused code
> Fix publishing helm chart

- gateway/transport/plugins/audit/audit.go
- gateway/transport/plugins/review/review.go
It fixes the error for reviewed connections when the client is performing a connect execution
```
rpc error: code = Internal desc = failed obtaining write ahead log for session <sid>
```
> Fix removal of wal state for connect type on jit reviews

- README.md
- Update tagline and add emojis for better visual appeal
- Add "Why Hoop?" section highlighting key benefits
- Include Quick Start guide and popular guides section
- Expand features list with links to documentation
- Add Docker installation instructions
- Reorganize and expand guides and features sections
- Improve overall readability and organization of content
> ref(readme): improved structure and content

- webapp/src/webapp/auth/views/signup.cljs
- webapp/src/webapp/events/segment.cljs
Identify user when email is first available
> Update Segment Identify Event Handler

- Dockerfile.dev
- Dockerfile.tools
- deploy/docker-compose/Dockerfile
Ref: https://github.com/hoophq/hoop/pull/443
> [agent] Bump gcloud cli and ubuntu base image to latest one

- webapp/src/webapp/webclient/codemirror/extensions.cljs
> ref(copilot): ensure output for language with prompt

- common/grpc/client.go
- gateway/api/runbooks/runbooks.go
- gateway/api/runbooks/templates/config.go
- gateway/api/runbooks/templates/git.go
- gateway/go.mod
- Add option to include known hosts content through the plugin runbook configuration (GIT_SSH_KNOWN_HOSTS)
- Remove unecessary sentry exception
> Add hosts key check callback function instead of relying in local known_hosts file

- gateway/slack/service.go
> chore: Create maxGroupsSize logic in SlackService

- .github/workflows/release.yml
- Makefile
- ci webapp step: update java to version 21
- ci webapp step: update clojure tools to 1.12.0.1479
- ci webapp step: update node to version 20
> chore(ci) update webapp ci tool versions

- gateway/api/runbooks/templates/template_funcs.go
- webapp/package.json
- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/webclient/runbooks/form.cljs
This PR contains the textarea as a new value to runbooks, and the implementation to accept it in the web app.
> [FEAT]: New type value for runbooks

- client/proxy/mysql.go
It defaults to to the max size of a MySQL packet which is 3 bytes (header size)
> [client] Increase the max packet size to 16MB that proxy clients are allowed to process

- deploy/docker-compose/Dockerfile
- deploy/helm-chart/chart/gateway/templates/secret-configs.yaml
- Add /opt/hoop/bin to PATH on hoophq/hooplabs image
> [deploy] Add migration configuration to helm-chart

- agent/secretsmanager/vault.go
- Introduced `VAULT_APP_ROLE_ID` and `VAULT_APP_ROLE_SECRET_ID` to vault/agent integration
- Access Tokens are obtained dynamically when App Role is configured
> Add Vault App Role integration to obtain tokens dynamically

- webapp/src/webapp/connections/views/connection_form_modal.cljs
- webapp/src/webapp/connections/views/form/application.cljs
- webapp/src/webapp/connections/views/form/custom.cljs
- webapp/src/webapp/connections/views/form/database.cljs
- webapp/src/webapp/connections/views/form/ssh.cljs
- webapp/src/webapp/connections/views/form/tcp.cljs
- webapp/src/webapp/shared_ui/sidebar/main.cljs
- Copy in the TCP and SSH creating connections
- Fix the Dashboard available in the side menu collapsed
> [FIX]: Copy in the tcp and ssh create connections

- webapp/package-lock.json
Changes provided by `npm audit fix` command
> [webapp] update webapp packages to fix vulnerabilities

- client/cmd/login.go
- gateway/api/localauth/login.go
- gateway/api/localauth/register.go
- gateway/api/openapi/types.go
- gateway/api/user/user.go
- Refactor localauth to use own local user type
- Refactor openapi.User attribute to Password
> Add local authentication to cli login action

- deploy/helm-chart/chart/gateway/templates/secret-configs.yaml
- Add missing configurations: API_KEY, DLP_PROVIDER, MSPRESIDIO_*, WEBAPP_USER_MANAGEMENT
- Remove unused configurations: MAGIC_BELL_*, SMTP_*, PLUGIN_REGISTRY_URL, PYROSCOPE_*
> [helm-chart] Add missing helm configurations

- README.md
The README.md file has been refactored to update the features, benefits, and installation instructions of the project. This includes adding new features such as zero trust access, real-time data masking, granular access control, audit logging, chatops integration, and multi-cloud support. The "Why Hoop?" section has been updated to highlight the simplified access management, enhanced security, compliance made easy, and developer productivity benefits of the project. The installation instructions have also been updated to include creating a JWT secret for authentication and downloading and running the project using Docker Compose.
> Refactor README.md to update features, benefits, and installation

- gateway/api/login/login.go
This PR applies some adjustments for the login flow as explained the bullet points below:
- when creating the context, we first get the user by email for when the user is not yet synced with the IDP, then the context is created as before, but covering that invitation process
- remove inforcement on user having to be active when first logging in, this is an old behavior and is not required anymore
- change place we get the user groups to sync in the database to be consistent with the new context adjustment documented in the first item
- sync the user subject with the idp always
- sync the email verified field from a user with the IDP
- update user status properly when the user is invited
> fix(login) context and rules for invited user consistency with IDPs

- gateway/analytics/events.go
- gateway/api/integrations/jira.go
- gateway/api/server.go
- gateway/api/session/session.go
- gateway/jira/jira.go
- webapp/package.json
- webapp/src/webapp/app.cljs
- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/connections/views/create_update_connection/connection_details_form.cljs
- webapp/src/webapp/db.cljs
- webapp/src/webapp/events/jira_integration.cljs
- webapp/src/webapp/plugins/views/manage_plugin.cljs
- webapp/src/webapp/plugins/views/plugin_configurations/access_control.cljs
- webapp/src/webapp/plugins/views/plugin_configurations/ask_ai.cljs
- webapp/src/webapp/plugins/views/plugin_configurations/jira.cljs
- webapp/src/webapp/plugins/views/plugins_configurations.cljs
- webapp/src/webapp/routes.cljs
- webapp/src/webapp/shared_ui/sidebar/constants.cljs
- webapp/src/webapp/shared_ui/sidebar/navigation.cljs
- webapp/src/webapp/subs.cljs
Changes:
Backend
- Moved logic content creation in session (Post) to inside the function CreateIssue of Jira, to keep all things of integration together;
- Added EventTrack of POST and PUT Jira integration;
- Fixed when trying to GET integration receiving error not found 404 when there is no integration Jira
Frontend
- Standardize all plugins layout;
- Create Jira integration flow;
- Separate integration from plugins in the side menu;
- Enable Reviews as not enterprise feature (JIT) - (I will talk with @feraio to fix it in Figma as well)
> [FEAT] JIRA Integration (frontend)

- deploy/helm-chart/chart/gateway/templates/deployment.yaml
- rootfs/usr/local/bin/hoop-default-agent.sh
- Add check to validate the liveness of the gateway before starting the default agent
> [helm] fix defaultAgent spec

- gateway/api/runbooks/templates/templates.go
Change regexp to match the attribute of a template with more precision.
> [gateway] Enhance runbook attribute matcher

- .env.sample
- gateway/analytics/segment.go
- gateway/appconfig/appconfig.go
- Remove the limitation of not tracking at localhost
- add an env var to configure if tracking is allowed or not
> feature(tracking) do not track app config

- gateway/api/connections/connections.go
- gateway/api/guardrails/guardrails.go
- gateway/api/integrations/jira.go
- gateway/api/openapi/autogen/docs.go
- gateway/api/openapi/types.go
- gateway/guardrails/guardrails.go
- gateway/guardrails/guardrails_test.go
- gateway/models/connections.go
- gateway/models/guadrails.go
- rootfs/app/migrations/000026_guardrails_rules_description.down.sql
- rootfs/app/migrations/000026_guardrails_rules_description.up.sql
[gateway] Update openapi docs
[gateway] Add description attribute to guardrails resource
> [gateway] Fix bug on fetching guardrail rules to scope resources to organization

- gateway/transport/plugins/webhooks/microsoftteams.review.create.json
- gateway/transport/plugins/webhooks/webhooks.go
> Use Adaptive Cards when sending reviews to MS teams

- gateway/api/login/login.go
- gateway/security/idp/authenticator.go
- gateway/security/idp/gsuite.go
It allows syncing groups from Google Gsuite when the scope `https://www.googleapis.com/auth/admin.directory.group.readonly` is present.
- Pagination ( it will be included in the next release )
> Add integration with Google Gsuite to sync groups when users sign in

- gateway/pgrest/plugins/helpers.go
- gateway/security/idp/gsuite.go
- remove indexer plugin to the list of default plugins to enable
> Fetch groups using pagination when fetching Gsuite groups

- webapp/src/webapp/connections/helpers.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/connections/views/connections_filter.cljs
- Add a break line when is filesystem SSH_PRIVATE_KEY
- Add subtype to search in the connections list
> [FIX]: General fixes

- webapp/package.json
- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/guardrails/main.cljs
> fix(input): allow users to see the text of password inputs

- webapp/package.json
- webapp/src/webapp/events/database_schema.cljs
- webapp/src/webapp/webclient/aside/database_schema.cljs
- webapp/src/webapp/webclient/panel.cljs
- Allow to see schema even with review on
- Fix the problems with select database
> fix(database-schema): select database when clicked at one of them

- webapp/src/webapp/app.cljs
- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/events/license.cljs
- webapp/src/webapp/routes.cljs
- webapp/src/webapp/settings/license/panel.cljs
- webapp/src/webapp/shared_ui/sidebar/navigation.cljs
Screenshots for both when the license is oss and enterprise
> License management page

- webapp/package.json
- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/components/accordion.cljs
- webapp/src/webapp/components/modal.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- New UI for options in the connection list
- Add Delete method for hoop run connections
> refactor(connection list): modify options in the connection list

- gateway/analytics/segment.go
- gateway/api/localauth/register.go
- gateway/api/login/login.go
This adds the anon id to the identify method
> fix(tracking) adjust identify to work with anon id

- gateway/api/connections/connections.go
- gateway/api/connections/queries_schema.go
- Removed debug function;
- It's unnecessary to send the DB name for MySQL and MSSQL when trying to get database schema.
> stop to send dbname to mysql and mssql to get database schema

- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/events/connections.cljs
> feature(connections) add tags filter to connections page

- webapp/src/webapp/webclient/quickstart.cljs
> feature(editor) add empty view for non admin users

- webapp/src/webapp/audit/views/session_details.cljs
> feat(session details): add jira link

- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/events/audit.cljs
> feat(session details): add verifier of size before opening a session details

- gateway/api/apiroutes/router.go
- gateway/api/apiroutes/tracing.go
- gateway/api/runbooks/runbooks.go
- gateway/api/server.go
- gateway/api/session/run-exec.go
- gateway/api/session/session.go
- gateway/review/api.go
- gateway/storagev2/core.go
- gateway/transport/interceptors/auth/auth.go
- gateway/transport/interceptors/tracing/tracing.go
- webapp/package-lock.json
- Remove /api/healthz from the tracing routes
- Add connection-subtype tracing span
- Add server context attributes to http tracing
> [gateway] Add user context attributes to http tracing

- webapp/package.json
- webapp/src/webapp/events/audit.cljs
> fix(session details): fix loading in loop in session details of connect verb

- common/license/license.go
- gateway/api/connections/connections.go
- gateway/api/connections/queries_schema.go
- gateway/api/integrations/issuetemplates.go
- gateway/jira/assetsapi.go
- webapp/package.json
- webapp/src/webapp/events/database_schema.cljs
- webapp/src/webapp/events/jira_templates.cljs
- webapp/src/webapp/jira_templates/cmdb_table.cljs
- webapp/src/webapp/jira_templates/create_update_form.cljs
- webapp/src/webapp/jira_templates/prompt_form.cljs
- webapp/src/webapp/webclient/aside/database_schema.cljs
- webapp/src/webapp/webclient/panel.cljs
- Fixed problem with JSON result from MongoDB
- Resized the quantity result by request in JIRA CMDB
- Changed object type by object type ID
- Changed the flow of Jira templates, now always showing a loading to download the fields of CMDB when needed.
> refactor(jira templates): change UX of jira template

- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/events/audit.cljs
- webapp/src/webapp/events/jira_templates.cljs
- webapp/src/webapp/jira_templates/basic_info.cljs
- webapp/src/webapp/jira_templates/create_update_form.cljs
- webapp/src/webapp/jira_templates/helpers.cljs
- webapp/src/webapp/jira_templates/loading_jira_templates.cljs
- webapp/src/webapp/jira_templates/prompt_form.cljs
- webapp/src/webapp/jira_templates/workflow_info.cljs
- webapp/src/webapp/webclient/panel.cljs
- Added workflow transition status to the Jira template form.
- Fixed date type parsing prompts to correctly convert to an ISO string while preserving the -0 timezone.
- Resolved the issue with session re-runs when a connection has a Jira template attached.
> [FEAT] Workflow transition status in the jira template form

- gateway/jira/issuesapi.go
- gateway/jira/types.go
- gateway/transport/extensions/extension.go
- webapp/package-lock.json
- webapp/src/webapp/jira_templates/workflow_info.cljs
> [gateway] It match name of transition issues based on the transitioned object

- gateway/api/openapi/autogen/docs.go
- gateway/api/openapi/types.go
- gateway/api/server.go
- gateway/api/session/session.go
- gateway/models/session.go
- Add endpoint `PATCH /api/sessions/:sid/metadata`
> [gateway] Allow mutating the session metadata attribute

- gateway/api/connections/helpers.go
- gateway/api/connections/helpers_test.go
- gateway/api/connections/queries_schema.go
- gateway/api/openapi/types.go
- webapp/package.json
- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/events/database_schema.cljs
- webapp/src/webapp/shared_ui/sidebar/navigation.cljs
- webapp/src/webapp/webclient/aside/database_schema.cljs
- Remove indexes from database schema:
Database compatible versions
PostgreSQL:
Recomendação: PostgreSQL 8.0 ou superior
PostgreSQL 9.x, 10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x
MySQL:
Recomendação: MySQL 5.1 ou superior
MySQL 5.6, 5.7, 8.0.x
SQL Server (MSSQL):
Recomendação: SQL Server 2008 ou superior
SQL Server 2012, 2014, 2016, 2017, 2019, 2022
Oracle:
Recomendação: Oracle 10g ou superior
Oracle 10g, 11g, 12c, 18c, 19c, 21c
MongoDB:
Usa getCollectionNames() e findOne()
Recomendação: MongoDB 2.6 ou superior
MongoDB 2.6, 3.0, 3.2, 3.4, 3.6, 4.0, 4.2, 4.4, 5.0
> refactor(database schema): remove indexes from database schema

- gateway/api/openapi/autogen/docs.go
- gateway/api/proxymanager/proxymanager.go
- Retrieve the connection using access control rules
> [gateway] fix nil pointer exception introduced by 1.31.34 when connecting via proxy manager

- agent/controller/agent.go
- agent/controller/terminal-exec.go
- agent/controller/terminal.go
- client/cmd/connect.go
- gateway/transport/plugins/audit/audit.go
- Improve hoop connect to proper restore the term when receiving an interrupt from the OS
> Improve handling exit code through agent and gateway

- common/mssqltypes/sqlbatch.go
This PR fixes an edge case in SQL batch header parsing where the packet sequence number resets (exceeds 255). Previously, the code would incorrectly attempt to parse stream headers from subsequent packets in a multi-packet sequence.
Changes:
- Added length validation before parsing ALL_HEADERS to prevent incorrect header parsing
- Added clarifying comments about stream header presence rules in MSSQL protocol
- Improved code readability with additional spacing and comments
According to the MSSQL protocol specification, stream headers MUST only be present in the first packet of requests that span multiple packets. This change ensures we follow this requirement correctly, particularly in cases where the packet sequence number wraps around.
Testing:
- Tested with long SQL queries that span …
> Fix SQL batch header parsing for multi-packet sequences

- client/proxy/tcp.go
- gateway/slack/service.go
- gateway/transport/connectionstatus/connectionstatus.go
- gateway/transport/plugins/slack/events.go
- gateway/transport/plugins/slack/slack.go
- gateway/transport/server.go
- Propagate TCP port properly when using hoop connect
- Slack logging enhancement
- Fix pre-connect to return error and remove sentry for these kind of failures
> Small Bugfixes and Enhancements

- client/cmd/login.go
- gateway/api/session/session.go
- gateway/slack/events.go
- gateway/slack/service.go
- gateway/transport/client.go
- gateway/transport/plugins/slack/events.go
- gateway/transport/plugins/slack/slack.go
- webapp/src/webapp/components/snackbar.cljs
[gateway] Do not persist session in case of a failure when parsing Jira fields
[webapp] Fix snackbar from overflowing error messages
> [gateway] Fix sending review slack approved messages when approving via Webapp

- deploy/aws/hoopdev-platform.template.yaml
This PR make the cloud formation aligned with AWS market place requirements
> [deploy/aws] Add imageid as parameter, default egress to all security groups and ingress cidr as parameter

- webapp/package.json
- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/components/tooltip.cljs
> [FIX] Review groups overflowing jira template link

- _libhoop/libhoop.go
- _libhoop/proxy/ssh/types/types.go
- agent/controller/agent.go
- agent/controller/ssh.go
- client/cmd/admin/admin.go
- client/cmd/admin/create-conn.go
- client/cmd/connect.go
- client/cmd/login.go
- client/proxy/defaults.go
- client/proxy/ssh.go
- common/proto/agent/agent.go
- common/proto/client/client.go
- common/proto/const.go
- common/proto/types.go
- gateway/api/openapi/types.go
- gateway/api/serverinfo/serverinfo.go
- gateway/appconfig/appconfig.go
- gateway/transport/agent.go
- scripts/dev/Dockerfile
- scripts/dev/entrypoint.sh
- scripts/dev/run.sh
This PR adds SSH connection support to Hoop, allowing users to establish secure SSH connections through the platform. The implementation includes both client and agent-side changes to handle SSH protocol communication.
- Added new SSH connection type and related protocol messages
- Implemented SSH server proxy with support for password authentication
- Added environment variable validation for SSH connections (HOST, USER, and either PASS or AUTHORIZED_SERVER_KEYS)
- Configured default SSH port (2222) for local connections
- Added SSH connection handling in the agent controller
- Added development environment support for testing SSH connections
- Introduced SSH_CLIENT_HOST_KEY to propagate the server host key when serving the SSH local server
- SSH server implementation uses Go's …
> Add native SSH proxy

- client/cmd/connect.go
- gateway/review/service.go
- gateway/slack/service.go
- gateway/transport/plugins/slack/events.go
- webapp/package-lock.json
- Propagate the context of user properly when performing a review via Slack
* It fixes users from self approving reviews
- Persist the Slack ID when performing a review
> [hotfix] Improve Slack review flow

- gateway/api/login/login.go
- gateway/api/middleware.go
- gateway/api/server.go
- scripts/dev/entrypoint.sh
- [gateway] Add redirect check against the API_URL to prevent redirect attacks
> [gateway] Add security headers to protect from common security vulnerabilities

- gateway/api/server.go
- block regular users from listing guard rails and users resources
> Block unauthorized access to admin resources from regular users

- rootfs/usr/local/bin/bash
This Pull Request permits executing bash with a sourced pre exec script.
It's useful to add setup scripts before the execution of sessions
> [agent] Add custom bash with PRE_EXEC source script

- agent/controller/agent.go
- agent/controller/sys/dbprovisioner.go
- client/cmd/connect.go
- common/proto/agent/agent.go
- common/proto/client/client.go
- common/proto/sys/sys.go
- gateway/api/integrations/aws/aws.go
- gateway/api/integrations/aws/provisioner.go
- gateway/api/openapi/autogen/docs.go
- gateway/api/openapi/types.go
- gateway/api/server.go
- gateway/appconfig/appconfig.go
- gateway/models/connections.go
- gateway/models/dbroles.go
- gateway/models/envvars.go
- gateway/transport/agent.go
- gateway/transport/sys/dbprovisioner.go
- rootfs/app/migrations/000032_dbrole_jobs.down.sql
- rootfs/app/migrations/000032_dbrole_jobs.up.sql
This PR introduces an automated user role provisioning system for AWS RDS database instances, enabling customers to securely provision standardized roles for their database instances without requiring manual setup.
1. **System Architecture**:
- Added new database role provisioning system that connects AWS integration with agent-based execution
- Created a job-based provisioning workflow that handles credential rotation and role creation
- Implemented a persistent job tracking system for auditability
2. **Agent Communication**:
- Added new message types for database provisioning between gateway and agent
- Implemented bidirectional communication channels for provisioning operations
- Created synchronous response handling for provisioning operations
3. **AWS Integration**:
- Enhanced AWS …
> AWS Database Role Provisioning Enhancement

- webapp/src/webapp/events/editor_plugin.cljs
- webapp/src/webapp/plugins/views/plugin_configurations/runbooks.cljs
- webapp/src/webapp/runbooks/views/panel.cljs
- webapp/src/webapp/webclient/components/header.cljs
- webapp/src/webapp/webclient/components/panels/runbooks.cljs
- webapp/src/webapp/webclient/events/connection_selection.cljs
- webapp/src/webapp/webclient/events/connections.cljs
- webapp/src/webapp/webclient/log_area/logs.cljs
- Update runbooks panel and header to include primary connection when fetching runbooks
- Modify connection selection events to trigger runbooks update
- Remove password type from git URL input in plugin configurations
- Add new event to update runbooks based on primary and selected connections
- Refactored logs view with improved action buttons and dropdown menu
> [FIX] Editor Bugs

- webapp/src/webapp/webclient/components/panels/runbooks.cljs
- webapp/src/webapp/webclient/components/search.cljs
- webapp/src/webapp/webclient/components/side_panel.cljs
- webapp/src/webapp/webclient/runbooks/list.cljs
Refactor Runbooks Panel State Management
- Add re-frame events and subscriptions for tracking runbooks data loading
- Replace Reagent atom with re-frame subscription in runbooks panel
- Update side panel component to support vertical scrolling
- Minor import cleanup in runbooks panel
Add dark mode support to search input component
- Enhance search input styling with dark mode text color
- Add dark:text-gray-12 class for improved dark mode readability
- Minor formatting improvements to class string definitions
> [FIX]: Minor fixes in the Editor

- webapp/package.json
- webapp/src/webapp/app.cljs
- webapp/src/webapp/integrations/aws_connect.cljs
- Refactor AWS Connect component to use Box with space-y-7 class
- Bump webapp version to 1.38.0
> [FIX] Update AWS Connect UI and version bump

- gateway/api/connections/helpers.go
- webapp/src/webapp/components/multiselect.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/connections/views/setup/additional_configuration.cljs
- webapp/src/webapp/connections/views/setup/connection_update_form.cljs
- webapp/src/webapp/connections/views/setup/events/db_events.cljs
- webapp/src/webapp/connections/views/setup/events/effects.cljs
- webapp/src/webapp/connections/views/setup/events/process_form.cljs
- webapp/src/webapp/connections/views/setup/events/subs.cljs
- webapp/src/webapp/connections/views/setup/tag_select_example.cljs
- webapp/src/webapp/connections/views/setup/tags_inputs.cljs
- webapp/src/webapp/connections/views/setup/tags_utils.cljs
- webapp/src/webapp/db.cljs
This PR implements a new user interface for tag management, using advanced selection components with support for grouped values and dynamic option creation.
- Added new `single-creatable-grouped` component for single selection with ability to create new options
- Refactored the tag system to use key-value format with appropriate validation
- Implemented validation for tag keys, allowing only letters, numbers, and hyphens
- Added utilities for tag management in separate file `tags_utils.cljs`
- Improved user experience with automatic value formatting and option grouping
- Organized code into smaller and more reusable components
- Added error message display for tag validation
The previous tag system used simple text fields without validation or suggestions, which made consistency and …
> Tag Management Improvement in Connections

- agent/controller/sys/dbprovisioner.go
- gateway/api/integrations/aws/aws.go
- gateway/api/integrations/aws/provisioner.go
- gateway/api/openapi/autogen/docs.go
- gateway/api/openapi/types.go
- Add validation to agent_id attribute to not allow empty values
> AWS Connect: Add integration with RDS aurora

- .github/workflows/pullrequest.yml
- Makefile
- gateway/api/integrations/aws/aws.go
- gateway/transport/sys/dbprovisioner.go
- change tests to output in json
> [hotfix] change incorrect import with libhoop

- gateway/api/openapi/types.go
- gateway/api/proxymanager/proxymanager.go
- webapp/connections_original.cljs
- webapp/package.json
- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/connections/views/connection_connect.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/connections/views/connection_review_modal.cljs
- webapp/src/webapp/connections/views/connection_settings_modal.cljs
- webapp/src/webapp/events/audit.cljs
- webapp/src/webapp/events/connections.cljs
This PR implements the new review flow for Hoop Access connections and fixes UI issues with connection modals.
1. New Connection Review Flow: Implemented a complete review mechanism for Hoop Access connections
- Added logic to check for review objects in connection sessions
- Implemented proper handling of revoke_at timestamps for reviewed connections
- Created a consistent flow for connection status management through reviews
2. Connection UI Improvements:
- Fixed an issue where connection modals would reopen during page navigation even when already minimized
- Improved how connection status is maintained across navigation
- Enhanced timer functionality to use revoke_at for accurate time calculation
- Updated connection handlers in connections.cljs to check and handle session reviews …
> Implement Hoop Access review flow and fix connection modal issues

- gateway/api/runbooks/helpers.go
This PR fix the UI from displaying the name of the runbook properly with the template error message.
> [hotfix] Fix runbooks api to display the connection list even when an error is found when parsing the template

- webapp/package.json
- webapp/src/webapp/connections/views/connection_connect.cljs
- webapp/src/webapp/events/connections.cljs
Enhance connection modal behavior to open only when connection is ready and improve error handling with modal display on failure
> Fix error handling on hoop access modal

- gateway/api/session/session.go
This PR prevents loading sessions in memory unnecessarily
> Add condition to load the session stream in memory if the client requested to

- webapp/package.json
- webapp/src/webapp/app.cljs
- webapp/src/webapp/components/searchbox.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/connections/views/tag_selector.cljs
- webapp/src/webapp/events/connections.cljs
- webapp/src/webapp/events/connections_filters.cljs
This PR enhances the Connection List interface with improved styling and adds new filtering capabilities:
- Redesigned connection list items with better borders and spacing
- Added rounded corners to first and last items
- Improved status indicator visibility
- Enhanced connection actions menu with clearer options
- A better responsive layout for the "Add Connection" button
- Added tag-based filtering system with a new tag selector component
- Implemented resource type filtering
- Added "Clear Filters" button when filters are active
- Enhanced search functionality with better filter integration
- Created a new tag selector component with search and multi-select capabilities
- Added new re-frame events for handling connection filtering
- Improved state management for filters and search
- …
> Improve Connection List UI and Add Tag Filtering

- webapp/package.json
- webapp/src/webapp/onboarding/events/aws_connect_events.cljs
- webapp/src/webapp/onboarding/setup_resource.cljs
- webapp/src/webapp/shared_ui/sidebar/main.cljs
- webapp/src/webapp/shared_ui/sidebar/navigation.cljs
- webapp/src/webapp/webclient/components/panels/connections.cljs
- Remove debug print statements from apply-sg-to-resource function
- Update AWS connection event handling to include webhook dispatch
- Update sidebar background colors for improved UI consistency
> AWS Connect Resources and Event Handling

- .gitignore
- client/go.mod
- client/go.sum
- client/proxy/mssql.go
- common/monitoring/monitoring.go
- gateway/api/apiroutes/tracing.go
- update toml lib to latest version (1.5.0+)
- remove tracing from /api/healthz endpoint
> [mssql] Warn instead of returning error when writing packet to client

- client/cmd/admin/get.go
- gateway/api/connections/helpers_test.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/webapp/connections/views/setup/additional_configuration.cljs
[cli] list total amount redacted items when listing sessions
> [dlp] fix displaying dlp fields for mspresidio type properly

- webapp/src/webapp/webclient/log_area/logs.cljs
This fixes a typo in the review message
> Fix typo in review message

- webapp/package.json
- webapp/src/webapp/onboarding/aws_connect.cljs
- webapp/src/webapp/onboarding/events/aws_connect_events.cljs
> Enhance error handling for AWS connection

- webapp/package.json
- webapp/src/webapp/plugins/views/plugin_configurations/runbooks.cljs
> update repository path handling in runbooks.cljs

- webapp/src/webapp/agents/panel.cljs
- webapp/src/webapp/events/agents.cljs
> Add delete functionality for agents with confirmation dialog

- gateway/api/apiroutes/auth.go
- gateway/api/login/login.go
- gateway/models/user_groups.go
- gateway/models/users.go
- gateway/security/idp/authenticator.go
- gateway/security/idp/gsuite.go
- Improve authentication logging
- closes #772
> Fix groups synchronization with Gsuite using cloud identity api

- webapp/src/webapp/webclient/components/connections_list.cljs
- webapp/src/webapp/webclient/components/database_schema.cljs
- webapp/src/webapp/webclient/panel.cljs
This PR implements critical optimizations to improve CodeMirror performance when used simultaneously with the database tree visualization. Previously, editor interaction was sluggish when the tree was expanded.
**1. Intelligent Debounce for Typing**
Added an adaptive debounce system that adjusts response time based on typing intensity:
- Intensive typing: 1500ms debounce
- Moderate typing: 1000ms debounce
- Occasional changes: 500ms debounce
This drastically reduces the number of re-renders during continuous editing.
**2. Memoization of Database Schema Conversion**
Implemented memoization for the convert-tree function, avoiding unnecessary recalculations of the database schema during editing:
- Database structure is processed only once
- Results are reused in subsequent renderings
- …
> Performance Optimizations for CodeMirror with Database Tree View

- webapp/src/webapp/webclient/panel.cljs
This PR addresses performance issues with CodeMirror when the database tree view is open. Previously, typing in the editor would become sluggish when the database schema tree was expanded. Additionally, there were issues with query execution where the RUN button wasn't always using the most current editor content.
** Switch from onUpdate to onChange for Editor Updates**
- Replace the custom handle_editor_update function with a direct onChange handler
- Simplify the update mechanism to use React's standard controlled component pattern
- Remove complex adaptive debounce in favor of a simpler 500ms fixed debounce
> Enhance CodeMirror Performance and Fix Query Execution Issues

- agent/controller/system/dbprovisioner/dbprovisioner.go
- common/grpc/client.go
- common/proto/system/dbprovisioner.go
- gateway/api/integrations/aws/aws.go
- gateway/api/integrations/aws/provisioner.go
- gateway/api/openapi/autogen/docs.go
- gateway/api/openapi/types.go
- gateway/api/runbooks/helpers.go
- gateway/api/runbooks/runbooks.go
- gateway/api/session/session.go
- gateway/models/dbroles.go
- gateway/pgrest/meta.go
- gateway/storagev2/types/types.go
- gateway/transport/interceptors/auth/auth.go
- gateway/transport/server.go
- gateway/transport/streamclient/agent.go
- gateway/transport/system/dbprovisioner.go
- rootfs/app/migrations/000036_dbroles_hook_status.down.sql
- rootfs/app/migrations/000036_dbroles_hook_status.up.sql
- webapp/package-lock.json
This PR introduces the execution of a hook if a git repository is configured and the runbook file `hoop-hooks/aws-connect-post-exec.runbook.py` is present.
- Removed unused attributes and tags from storagev2 types
- Remove unused functions
> AWS Connect: Trigger the execution of a Runbook hook as the last step of the provisioning

- webapp/package.json
- webapp/src/webapp/app.cljs
- webapp/src/webapp/features/access_control/views/group_form.cljs
- webapp/src/webapp/features/runbooks/events.cljs
- webapp/src/webapp/features/runbooks/main.cljs
- webapp/src/webapp/features/runbooks/subs.cljs
- webapp/src/webapp/features/runbooks/views/configuration_view.cljs
- webapp/src/webapp/features/runbooks/views/empty_state.cljs
- webapp/src/webapp/features/runbooks/views/runbook_form.cljs
- webapp/src/webapp/features/runbooks/views/runbook_list.cljs
- webapp/src/webapp/routes.cljs
- webapp/src/webapp/shared_ui/sidebar/main.cljs
- webapp/src/webapp/shared_ui/sidebar/navigation.cljs
This PR implements an enhanced interface for the Runbooks module, organizing content into two distinct tabs: "Connections" and "Configuration". The Connections tab allows for the management of paths for each connection, while the Configuration tab facilitates the Git repository setup for runbooks consumption.
- Improve user interface organization
- Simplify the connection path management flow
- Provide a dedicated space for Git repository configuration
- Allow greater flexibility in path configuration (including removal/clearing)
- Created tab structure in the main Runbooks component
- Simplified the form for managing paths, allowing both addition and removal
- Implemented Git configuration view with automatic loading of existing values
- Improved user experience by allowing empty path …
> Runbooks: Enhanced Interface with Connections and Configuration Tabs

- agent/controller/httpproxy.go
- agent/controller/mongodb.go
- agent/controller/mssql.go
- agent/controller/mysql.go
- agent/controller/postgres.go
- agent/controller/ssh.go
- agent/controller/terminal-exec.go
- agent/controller/terminal.go
- client/cmd/admin/create-conn.go
- [cli] Updating a command via cli will replace the redact types
- [libhoop] Improve Postgres and MSPresidio logging including the session id
> [agent] Propagate session id to all protocol functions

- webapp/src/webapp/audit/views/sessions_filtered_by_id.cljs
- webapp/src/webapp/auth/views/signup.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/events/ask_ai.cljs
- webapp/src/webapp/events/runbooks_plugin.cljs
- webapp/src/webapp/onboarding/main.cljs
- webapp/src/webapp/shared_ui/sidebar/main.cljs
- webapp/src/webapp/webclient/components/connections_list.cljs
- webapp/src/webapp/webclient/components/header.cljs
- webapp/src/webapp/webclient/components/panels/connections.cljs
- webapp/src/webapp/webclient/components/side_panel.cljs
- webapp/src/webapp/webclient/panel.cljs
- webapp/src/webapp/webclient/runbooks/form.cljs
- webapp/src/webapp/webclient/runbooks/list.cljs
This PR refactors the Runbooks functionality to improve user experience when working with connections that have specific access mode restrictions. It focuses on better UI responsiveness, proper permission handling, and enhanced layout management.
- Added permission checks for determining when connections should be available for web terminal or native client access
- Implemented connection filtering logic to exclude specific subtypes (`tcp` and `httpproxy`) and validate access modes
- Added functionality to automatically select the appropriate interface (runbooks editor or SQL editor) based on connection permissions
- Implemented proper button state management in header to indicate when actions are unavailable
- Added `cursor-not-allowed` styling for disabled elements to improve visual …
> Runbook Editor Improvements: Enhanced UI Responsiveness and Connection Management

- webapp/src/webapp/components/forms.cljs
- webapp/src/webapp/runbooks/views/template_dynamic_form.cljs
- webapp/src/webapp/runbooks/views/template_view.cljs
- webapp/src/webapp/webclient/runbooks/form.cljs
It adds a explicit value informing the user the default values that will be used when executing the runbook
> Propagate default value from API to runbook forms

- gateway/models/orgs.go
> Add explicit private schema to users table when getting organization

- gateway/api/proxymanager/proxymanager.go
- gateway/models/user_context.go
- gateway/storagev2/clientstate/clientstate.go
- gateway/transport/proxymanager.go
Update the proxymanager state uuid properly, bug introduced on PR #834
> Fix issue when connecting with proxy manager / desktopapp

- webapp/package.json
- webapp/src/webapp/events/audit.cljs
Refactor event stream logic to handle different session verbs and connection subtypes
> Implement parsed database protocol visualization

- client/proxy/mysql.go
- scripts/publish-release.sh
- Add wider commit messages when publishing new releases
- Closes #831
> mysql: Fix client hang when connection ID cannot be found

- deploy/helm-chart/chart/agent/templates/deployment.yaml
- deploy/helm-chart/chart/agent/values.yaml
- deploy/helm-chart/chart/gateway/templates/deployment.yaml
- deploy/helm-chart/chart/gateway/values.yaml
allow configuring deployment annotations with values.yaml for gateway and agent helm charts
> [helm-charts]: allow configuring deployment annotations

- gateway/api/integrations/aws/aws.go
- gateway/api/integrations/aws/provisioner.go
- gateway/api/openapi/autogen/docs.go
- gateway/api/server.go
- gateway/models/connections.go
- gateway/models/envvars.go
- gateway/models/plugins.go
- gateway/transport/interceptors/auth/auth.go
- Fix connections provisioning with plugin review
- Remove unused route POST /integrations/aws/iam/verify
> Remove persistence of AWS Iam Keys and RDS database root credentials

- webapp/src/webapp/connections/views/setup/connection_update_form.cljs
- webapp/src/webapp/connections/views/setup/events/process_form.cljs
Fix SSH connection update form authentication method persistence and form validation issues. This PR resolves problems where the SSH authentication method would reset to "Username & Password" when editing existing connections, and where the Save button would not function due to form ID inconsistencies.
Fixes #
- **SSH Authentication Method Persistence**: Added logic in `process-connection-for-update` to automatically detect and set the correct SSH authentication method based on existing connection data
- **Dynamic Form ID Detection**: Updated `connection_update_form.cljs` to dynamically identify the correct form ID based on connection type/subtype instead of using hardcoded form IDs
- **Field Cleanup Logic**: Implemented automatic cleanup of unused SSH credential fields based on selected …
> Fix SSH connection update form authentication persistence and save functionality

- webapp/package-lock.json
- webapp/package.json
- webapp/src/webapp/audit/views/session_data_raw.cljs
- webapp/src/webapp/audit/views/session_data_video.cljs
- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/db.cljs
- webapp/src/webapp/events/audit.cljs
- webapp/src/webapp/shared_ui/sidebar/constants.cljs
- webapp/src/webapp/subs.cljs
This PR introduces a new tabbed interface for terminal sessions (command-line and custom types), providing users with two viewing modes: Video (existing asciinema player) and Logs (new text-based view with ANSI escape code interpretation).
The Logs tab displays session output as continuous text with proper ANSI formatting, making it easier to read, search, and copy terminal output. This complements the existing video player view while providing a more accessible format for text-based terminal sessions.
- **Added tabs interface** for command-line and custom session types with "Logs" and "Video" options
- **Implemented ANSI interpreter** using `fancy-ansi` library to properly render terminal colors and formatting
- **Created continuous text view** for logs similar to existing logs-container …
> feat: Add Video/Logs tabs with ANSI interpretation for terminal sessions

- webapp/src/webapp/events/database_schema.cljs
- webapp/src/webapp/features/access_control/main.cljs
- webapp/src/webapp/features/access_control/subs.cljs
- webapp/src/webapp/features/access_control/views/group_list.cljs
- webapp/src/webapp/http/request.cljs
This PR includes two major improvements to the codebase: enhanced error handling in HTTP requests and database schema events, plus a unified approach to group management in the access control feature.
The refactor simplifies error handling across the application by providing complete error objects to failure callbacks and streamlines HTTP response parsing. Additionally, it enhances the access control feature by combining groups from multiple data sources for better visibility and management.
- Simplified HTTP response parsing by removing complex multimethod dispatch
- Consolidated JSON and text response handling into unified `parse-json-response` function
- Enhanced error handling to provide complete error objects instead of just message strings
- Improved network error handling with …
> Refactor error handling and unify group management

- gateway/api/openapi/autogen/docs.go
- gateway/api/openapi/types.go
- gateway/api/serverconfig/auth.go
- gateway/models/server_auth_config.go
- rootfs/app/migrations/000042_auth_provider_type.down.sql
- rootfs/app/migrations/000042_auth_provider_type.up.sql
Add provider_name attribute to `/api/serverconfig` endpoints
> serverauth: Add provider_name attribute to api

- webapp/package.json
- webapp/src/webapp/webclient/log_area/main.cljs
Fix the behavior that was blocking tabular logs
> hotfix: show tabular logs

- gateway/idp/core.go
- gateway/transport/plugins/audit/wal.go
It fixes api key errors for gRPC connections
> hotfix: propagate organization when loading idp provider context for api key

- deploy/aws/hoopdev-platform.template.yaml
Revert AWS cloud formation changes removing EBS volume introduced in #962
> Revert AWS Cloud Formation EBS volumes

- .github/workflows/cla.yml
Include Matheus and Chico to CLA allowlist
> Add Matheus and Chico to CLA allowlist

- webapp/src/webapp/components/virtualized_list.cljs
- webapp/src/webapp/connections/views/connection_list.cljs
- webapp/src/webapp/webclient/components/panels/multiple_connections.cljs
- webapp/src/webapp/webclient/components/primary_connection_list.cljs
- webapp/src/webapp/webclient/panel.cljs
- Introduced a new `virtualized-list` component to efficiently render only visible items in a list, improving performance for large datasets.
- Updated `connection_list` view to utilize the new `virtualized-list` component, enhancing the user experience by reducing rendering time and improving scroll performance.
- **Applied virtualization to webclient components** (`primary_connection_list` and `multiple_connections`) for consistent performance across the application.
- Implemented props for item height, container height, and overscan to customize the rendering behavior based on the application's needs.
This PR introduces a virtualized list component to dramatically improve performance when rendering large numbers of connections (1000+). The virtualization technique renders only visible …
> Performance: Implement virtualized list for connection rendering

- webapp/src/webapp/audit/views/session_details.cljs
- webapp/src/webapp/reviews/review_detail.cljs
Fixed a bug where the ClipboardJS success event was being triggered multiple times (5x) when clicking the "Copy Link" button. This was caused by event listeners being attached on every component re-render without proper cleanup.
- Moved ClipboardJS initialization inside `r/with-let` block to ensure it's created only once per component lifecycle
- Added proper cleanup by calling `.destroy()` in the `finally` block when component unmounts
- Applied the same fix to both `session_details.cljs` and `review_detail.cljs` files
- **Browser(s)**: Chrome, Firefox, Safari
The issue occurred because the ClipboardJS instance was being created outside the component lifecycle, and the event listener was being attached on every render without being removed. By moving the initialization …
> Fix ClipboardJS multiple event listener executions on Copy Link button

- webapp/src/webapp/audit/views/session_details.cljs
Re-run doesn't work with JIRA because we don't have the JIRA values at the moment of re-running inside the session details.
> Removing re-run from a session created with JIRA.

- deploy/helm-chart/chart/gateway/templates/deployment-postgres.yaml
- deploy/helm-chart/chart/gateway/values.yaml
> Helm: Add Postgres option deployment with volume persistence

- gateway/api/login/oidc/login.go
- gateway/api/login/saml/login.go
- webapp/src/webapp/app.cljs
This PR addresses a critical security vulnerability in the authentication flow by migrating from passing access tokens via URL query parameters to using secure cookies. This change prevents token exposure in browser history, server logs, and referrer headers while maintaining the same authentication functionality.
- **Enhanced authentication callback security**: Modified `LoginCallback` to use cookies instead of URL parameters for web applications
- **Conditional cookie implementation**: Only uses cookies for web app redirects (non-CLI clients)
- **Secure cookie configuration**: Implements secure cookie with appropriate flags (secure, httpOnly settings)
- **Cookie utility functions**: Added `get-cookie-value` and `clear-cookie` helper functions
- **Updated authentication handlers**: …
> Use secure cookies instead of URL tokens for authentication

- webapp/src/webapp/events/agents.cljs
Before this change, when the `agents->generate-agent-key` request failed, the UI would remain in a loading state, disabling the input field and submit button, preventing users from retrying without refreshing the page.
This PR adds proper error handling to reset the loading state and show error feedback.
-  Add `on-failure` handler to `agents->generate-agent-key` event.
- **Browser(s)**: Chrome
(_After trying to create an agent with an invalid name, users couldn't change the name and submit again_)
> fix: Handle generate-agent-key event failure

- client/go.mod
- deploy/aws/hoopdev-platform.template.yaml
Includes Presidio deployment to Cloud Formation deployment
- Includes Presidio deployment to Cloud Formation deployment
- Included 20GB disk to root volume
- Added docker installation package
- Bump go modules
> Add option to include Presidio deployment to Cloud Formation

- webapp/package.json
- webapp/src/webapp/connections/views/setup/events/db_events.cljs
- webapp/src/webapp/connections/views/setup/events/process_form.cljs
- webapp/src/webapp/connections/views/setup/network.cljs
This PR adds a new "Allow insecure SSL" toggle switch to the HTTP Proxy connection setup form. This feature allows users to skip SSL certificate verification for HTTPS connections, which is useful for development environments or internal services with self-signed certificates.
The toggle is OFF by default and sends the value as an `INSECURE` environment variable to the backend (`"true"` or `"false"` as base64-encoded strings).
- Added `Switch` component from Radix UI to the HTTP Proxy credentials form
- Created new Re-frame event `:connection-setup/toggle-network-insecure` to manage the switch state
- Modified `process-form.cljs` to include `INSECURE` environment variable in httpproxy connections
- Updated `extract-http-credentials` function to parse the insecure flag when editing …
> Add insecure SSL flag for HTTP Proxy connections

- webapp/src/webapp/subs.cljs
- webapp/src/webapp/webclient/components/connection_dialog.cljs
- webapp/src/webapp/webclient/components/database_schema.cljs
- webapp/src/webapp/webclient/components/header.cljs
- webapp/src/webapp/webclient/components/panels/database_schema.cljs
- webapp/src/webapp/webclient/events/primary_connection.cljs
- webapp/src/webapp/webclient/panel.cljs
This PR introduces a new **Compact Terminal UI** layout as an alternative to the classic sidebar layout. The new layout maximizes editor space by replacing the sidebar with a command palette for connection selection and adds a collapsible Database Schema panel on the left side.
- **Feature Flag System**: Added `compact-terminal-ui` localStorage-based feature flag with subscription `:webclient/use-compact-ui?`
- **Connection Dialog Component**: Created `connection_dialog.cljs` using `cmdk` library for fast connection search and selection
- **Layout Switcher**: Added header button to toggle between Classic and Compact layouts with page reload
- **Dual Layout Support**: Implemented conditional rendering for both Classic (sidebar) and Compact (full-width editor) layouts
- **Collapsible …
> New compact Terminal UI 

- rootfs/app/migrations/000045_rdp_server_config.down.sql
- rootfs/app/migrations/000045_rdp_server_config.up.sql
- scripts/dev/run.sh
Change the rdp port in the codebase to follow the standard and fix migration
Fixes #
- Fix migration error
- Fix Rdp port to follow the standard
- 
- **Browser(s)**: 
- **OS**:
---
> Fix RDP port to follow standard
