hoophq/hoop

README.md
Improved ux as users have fewer pages to navigate and can get started without leaving readme. I believe we should push this even further
=> [readme] add install instructions to readme

README.md
This improves the "About hoop.dev" section visually and adds a link to the full features list from our landing page so people can see what's available in our open-source versus what's available in enterprise plans.
=> docs(readme) add features list link to readme

common/proto/const.go, gateway/transport/plugins/audit/audit.go, gateway/transport/plugins/audit/wal.go, gateway/transport/plugins/review/review.go
It fixes reviewed sessions being closed on agent disconnections.
=> [hotfix] Drop write ahead log and cleanup sessions from memory properly

webapp/src/webapp/webclient/codemirror/extensions.cljs
check if both the prefix and suffix are empty. If they are, it sets the user content to "select <FILL_ME>". Otherwise, it uses the original prefix and suffix.
=> feat(copilot): add default query to empty editor

gateway/api/session/session.go
- added a verification at the controller level to allow admins only to see everyone's sessions
=> fix(session) reforce to only admins see everyones sessions

gateway/pgrest/review/review.go, gateway/review/service.go, gateway/transport/plugins/review/review.go, gateway/transport/plugins/review/review.oss.go, gateway/transport/plugins/review/review_test.go
- Move logic of validating jit expiration to GO to facilitate diagnosing time expiration issues
=> Fix race condition problem when approving concurrent jit access

gateway/api/webhooks/dashboard.go, gateway/appconfig/appconfig.go, gateway/transport/plugins/webhooks/webhooks.go
- Introduce `WEBHOOK_APPURL` env configuration
=> Allow customizing the svix client to send webhooks to a svix self hosted installation

gateway/security/idp/authenticator.go
This Pull Request allow JWT access tokens to be used in cases of access tokens obtained through grants where no resource owner is involved, such as the client credentials grant.
- It allow the check against the authorized to bypass in case there's a "gty" claim (Auth0 specific)
- Include the "client_id" claim to deny the request if it doesn't match the configured client_id
=> Allow bypassing authorized party check when validating client credentials flow with JWT access tokens for Auth0

gateway/api/openapi/types.go, gateway/api/runbooks/runbooks.go, gateway/api/session/session.go, gateway/pgrest/review/review.go, gateway/review/api.go, gateway/storagev2/types/types.go
This change will allow adding environment variables to the runtime of an execution.
- Remove the attribute `input_envvars` from displaying in the public api
=> Add runbook env vars primitives

gateway/transport/plugins/webhooks/microsoftteams.review.create.json, gateway/transport/plugins/webhooks/webhooks.go
- [gateway] Add attribute attachments[].content.type to AdaptiveCard when sending ms teams events
- [gateway] Add review simple structure to differentiate sessions with reviews when creating session.open events
=> Add attribute type AdaptiveCard when sending ms teams events

gateway/api/serverinfo/serverinfo.go, webapp/src/webapp/app.cljs, webapp/src/webapp/events/auth.cljs, webapp/src/webapp/routes.cljs, webapp/src/webapp/shared_ui/sidebar/navigation.cljs
This PR will ensure that sessions are reused when redirecting failed attempts to authenticate (401). It removes the `prompt=login` option when redirecting users to their identity providers.
Additionally, it makes sure to always prompt for the login screen when the user clicks on Logout.
More information in the [OpenID specification](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)
- Tested with local auth method
- Tested with Azure Entra ID
- Tested with Auth0
- Tested with multi tenant setup
=> Allow maintaining the session of identity providers

.github/workflows/release.yml, Makefile, gateway/analytics/intercom.go, gateway/analytics/runtime.go, gateway/api/openapi/types.go, gateway/api/user/user.go, webapp/src/webapp/events.cljs
Identity Verification stops anyone impersonating logged-in users or seeing their conversations.
=> Secure the Intercom messenger with Identity Verification

common/log/log.go, common/proto/const.go, gateway/api/session/session.go, gateway/clientexec/clientexec.go, gateway/transport/agent.go, gateway/transport/client.go, gateway/transport/extensions/extension.go, gateway/transport/interceptors/auth/auth.go, gateway/transport/streamclient/pluginruntime.go
- Revert emitting stacktraces when logging errors
- Fix bug when guardrule returns a match over api execution
=> Allow performing plain execution on connection over internal routes using clientexec

client/config/config.go, webapp/src/webapp/events/connections.cljs
It propagate the grpcURL properly when configuring the hoop command line by using the schema (grpc or grpcs).
Related to #563
=> [Webapp] Allow desktop app to work with local installations

webapp/src/webapp/components/forms.cljs
This brings back the natural behavior for the input type password to always hide the password. There are internal discussions to run before proceeding because this behavior has other uses in the application.
Closes #546
=> refactor(forms) make password field have natural behavior

webapp/Makefile, webapp/README.md, webapp/package-lock.json, webapp/package.json, webapp/src/webapp/connections/constants.cljs
- Add the `-t` option that force pseudo terminal allocation
- Add `-o StrictHostKeyChecking=accept-new` to avoid prompting for accepting public keys interactively
=> Allow SSH connections to work in the Webapp (ad-hoc executions)

client/go.mod, deploy/docker-compose/.env-sample, deploy/docker-compose/docker-compose.yml, deploy/docker-compose/rootfs/usr/local/bin/gateway-healthcheck.sh, deploy/docker-compose/rootfs/usr/local/bin/run-agent.sh, gateway/analytics/segment.go, gateway/api/apiroutes/tracing.go, gateway/api/middleware.go, gateway/api/session/session.go, gateway/go.mod
- fix segment to propagate environment names properly
- prevent errors when parsing user context on http tracing
- remove legacy cors header x-backend-api
Related to #625: it improves the response from the server to avoid returning empty OK responses.
=> [gateway] encode session response manually to obtain any error beforehand

gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/api/session/session.go, webapp/src/webapp/audit/views/session_data_raw.cljs, webapp/src/webapp/audit/views/session_details.cljs, webapp/src/webapp/events/audit.cljs, webapp/src/webapp/utilities.cljs
- Introduced option `event_stream=base64` to obtain the parsed content as base64 to avoid breaking compatibility with clients
- The option `event_stream=utf8` will continue to work as is, but it will not work properly for shell connections that contains invalid characters
- Change the webapp to use `base64`option and decode the content when rendering the session details
=> [gateway] Fix session details to decode base64 sessions to avoid invalid characters json error encoding

gateway/api/session/session.go, gateway/models/session.go, gateway/transport/plugins/audit/wal.go
This change speed the listing session endpoint pre-computing the size of events
=> [gateway] Add computed event size when listing sessions

gateway/transport/agent.go, gateway/transport/plugins/audit/audit.go, gateway/transport/plugins/audit/wal.go, gateway/transport/plugins/types/types.go, webapp/package-lock.json
The session closure function was executing multiple times concurrently, causing race conditions where incorrect exit codes would propagate through the system. Each subsequent execution would overwrite the previous exit code state, potentially masking the true process outcome.
=> [gateway] propagate exit code properly when persisting sessions

deploy/helm-chart/chart/gateway/templates/secret-configs.yaml, gateway/api/connections/connections.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, webapp/README.md, webapp/package-lock.json, webapp/package.json, webapp/src/webapp/events/editor_plugin.cljs
- Add `default_database` attribute to prevent Webapp from obtaining the default database by parsing secrets attribute
- Add `npm run dev` instruction
- Add `INTEGRATION_AWS_INSTANCE_ROLE_ALLOW` configuration to helm
=> [security] prevent leaking sensitive information from connections by removing secrets on listing

client/cmd/admin/apiutils.go, client/cmd/admin/create-conn.go, client/cmd/admin/get.go, gateway/api/connections/connection_tags.go, gateway/api/connections/connections.go, gateway/api/connections/defaults.go, gateway/api/connections/helpers.go, gateway/api/connections/queries_schema.go, gateway/api/localauth/register.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/docs/api-connection.md, gateway/api/openapi/types.go, gateway/api/server.go, gateway/api/signup/signup.go, gateway/main.go, gateway/models/connection_tags.go, gateway/models/connections.go, rootfs/app/migrations/000034_tags_key_val.down.sql, rootfs/app/migrations/000034_tags_key_val.up.sql
- Add new attribute (`connection_tags`) to persist tags when managing connections
- Add `GET /api/connection-tags` endpoint to list all available tags of an organization
- Update cli to filter connections by tag selector
- Add `tagSelector` query string to filter connections by tags
- Add default system tags when creating the default organization
=> Add connection tags as key value attributes to connections

webapp/package.json, webapp/src/webapp/audit/views/session_details.cljs
This PR enhances the view of the session audit details by adding reviewer attribution information. Now, when sessions are approved or rejected, the system displays the email of the user who performed the review action, improving accountability and transparency in the audit workflow.
- Added display of reviewer email in the review group items when status is "APPROVED" or "REJECTED"
- Implemented tooltip for reviewer emails to handle long email addresses gracefully
- Adjusted styling and layout of review group items to accommodate the new information
- Added "relative" class to review group items for proper positioning of elements
- Review group items now display:
- Group name with tooltip for longer names
- Review status (PENDING, APPROVED, REJECTED)
- **New**: Reviewer email (when …
=> Display reviewer information in session audit details view

gateway/api/integrations/aws/aws.go
Prevents conflicts with customers that already have this role set
=> AWS Connect: Add prefix with Hoop to static cross account role

webapp/package.json, webapp/src/webapp/onboarding/aws_connect.cljs, webapp/src/webapp/onboarding/events/aws_connect_events.cljs, webapp/src/webapp/onboarding/setup_resource.cljs
This PR enhances the AWS Connect workflow by adding a new Accounts selection step between Credentials and Resources. Users can now select specific AWS accounts to scan for database resources, providing a more targeted discovery process.
- Added a new "Accounts" step in the AWS Connect workflow
- Implemented account selection UI with multi-select table
- Modified the RDS instances API call to filter by selected account IDs
- Fixed the loading screen to properly overlay only the content area while preserving the header and footer
- Improved error handling and display in resources data table
- Streamlined the workflow by removing the verify-credentials step
=> Add AWS Accounts Selection Step to Connect Workflow

client/cmd/admin/apiutils.go, client/cmd/admin/get.go, gateway/api/connections/connections.go, gateway/api/connections/helpers.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/api/session/parser.go, gateway/api/session/run-exec.go, gateway/api/session/session.go, gateway/models/session.go
- Allow applying filter the status and the approver e-mail of a review
- Regular users lists all sessions, the output is only displayed for owners or administrators
- Return review information when listing sessions
- Change tagSelector to `tag_selector` on connections
- [cli] Add session tabview to sessions
- [cli] Add query string parameter to query endpoints -q/--query
=> Allow applying review filters to sessions

webapp/package.json, webapp/src/webapp/audit/views/results_container.cljs, webapp/src/webapp/audit/views/session_details.cljs, webapp/src/webapp/components/data_grid_table.cljs, webapp/src/webapp/components/logs_container.cljs
This PR implements functionality to disable the copy capability (Ctrl+C) in two different components when download disable is on:
- DataGridTable: Added the allowCopy false parameter to prevent copying in the table
- LogsContainer: Enhanced the implementation of the existing, :not-clipboard? parameter to effectively prevent text copying
- data_grid_table.cljs: Added parameter to disable copy functionality in DataGridXL
- logs_container.cljs: Implemented multiple protections against text copying when :not-clipboard? is true:
- Added :on-copy event to prevent copying directly in the section
- Added select-none class to the container
- Added cross-browser styles for user-select: none
=> Disable copy functionality in specific components when disable download is on

gateway/api/integrations/aws/provisioner.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/transport/plugins/webhooks/const.go
- Use the port from the db instances instead of relying of the input from client
=> AWS Connect: Add custom webhooks when finishing the provisioning job

client/cmd/config/config.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/api/session/parser.go, gateway/api/session/session.go, gateway/jira/issuesapi.go, gateway/jira/issuesapi_test.go, gateway/models/session.go, gateway/storagev2/types/types.go, gateway/transport/interceptors/auth/auth.go, gateway/transport/plugins/audit/audit.go, gateway/transport/plugins/types/types.go, gateway/transport/server.go, rootfs/app/migrations/000035_session_connection_tags.down.sql, rootfs/app/migrations/000035_session_connection_tags.up.sql
- Add new Jira preset attribute value: `session.connection_tags.[key]`
- [cli] Allow obtaining the configuration attributes partially via hoop config view
Example of a preset configuration:
```json
{
"name": "mytemplate",
"description": "my template",
"project_key": "HT",
"request_type_id": "10005",
"issue_transition_name_on_close": "done",
"mapping_types": {
"items": [
{
"description": "Environment",
"type": "preset",
"value": "session.connection_tags.env",
"jira_field": "customfield_10051"
},
{
"description": "Team",
"type": "preset",
"value": "session.connection_tags.team",
"jira_field": "customfield_10052"
}
]
}
}
```
=> Propagate connection tags to the session

webapp/src/webapp/config.cljs, webapp/src/webapp/onboarding/aws_connect.cljs, webapp/src/webapp/onboarding/events/aws_connect_events.cljs
This PR adds integration with HashiCorp Vault Secrets Provider to the AWS Connect workflow, allowing users to expand environment variables in their connections using Vault dynamically.
- Added a new "Enable Vault Secrets Provider" toggle in the AWS Connect review step
- Added a Vault Path input field that appears when the toggle is enabled
- Created new re-frame events and subscriptions to manage Vault Secrets Provider state:
- `:aws-connect/toggle-secrets-manager`
- `:aws-connect/set-secrets-path`
- `:aws-connect/enable-secrets-manager`
- `:aws-connect/secrets-path`
- Updated the connection creation payload to include vault provider information when enabled:
```clojure
{:agent_id ""
:aws {:instance_arn ""
:default_security_group {:ingress_cidr ""}}
:connection_prefix_name ""
:job_steps …
```
=> Add Vault Secrets Provider integration to AWS Connect setup

webapp/package.json, webapp/src/webapp/jira_templates/create_update_form.cljs, webapp/src/webapp/jira_templates/helpers.cljs, webapp/src/webapp/jira_templates/mapping_table.cljs, webapp/src/webapp/jira_templates/preset_mapping_table.cljs
This PR implements connection tags mapping functionality for Jira templates, providing a more intuitive way to map connection tags to Jira fields. The implementation includes a preset mapping table, improved UI components, and better descriptions for the mapping process.
- Add preset mapping table for connection tags to Jira fields
- Implement connection tags loading and mapping functionality
- Refactor Jira templates to improve connection tags mapping descriptions
- Restructure components for better organization and maintainability
- Clean up unused event subscriptions and comments
- Bump package version to 1.42.0
This PR enhances the integration between our connection system and Jira, making it easier for users to configure and use Jira templates with proper field mappings.
=> Enhance Jira Templates with Connection Tags Mapping

gateway/api/guardrails/guardrails.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/models/guadrails.go, webapp/package.json, webapp/src/webapp/db.cljs, webapp/src/webapp/events/guardrails.cljs, webapp/src/webapp/guardrails/connections_section.cljs, webapp/src/webapp/guardrails/create_update_form.cljs, webapp/src/webapp/guardrails/helpers.cljs
This PR enhances the GuardRails API to support bidirectional relationships with Connections. Previously, Connections could reference GuardRails through their `GuardRailRules` array, but GuardRails couldn't directly reference their associated Connections.
- Added functionality to associate connections with guardrails directly through the API
- Modified `GetConnectionIDsForGuardRail` to return connection IDs instead of names
- Enhanced `SyncGuardRailConnections` to properly handle both connection IDs and names
- Fixed HTTP status code in POST response to match API documentation (201 Created)
- Improved error handling and added more detailed logging
- Made sure all connections are properly synced when creating or updating a guardrail
- Tested creating guardrails with connections (POST)
- …
=> Add bidirectional relationship between GuardRails and Connections

agent/controller/postgres.go, agent/controller/terminal.go, deploy/helm-chart/chart/gateway/templates/secret-configs.yaml, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/security/idp/authenticator.go, gateway/transport/plugins/audit/wal.go
- [libhoop] Refactor redact provider to support generic clients with codec types for various use cases
- [libhoop] Add MSPresidio statistics collection and propagation
- [libhoop] Configure partial content redaction in MSPresidio
- [libhoop] Enable structured content redaction via YAML encoder
- [libhoop] Implement context propagation for timeout control during redaction
- Add MSPresidio configuration to terminal console and Postgres
- Add IDP_GROUPS_CLAIM env configuration
=> [libhoop] Implement Postgres native redaction with MSPresidio

gateway/api/integrations/issuetemplates.go, gateway/api/openapi/types.go, gateway/models/jira_issue_templates.go, webapp/package-lock.json, webapp/package.json, webapp/src/webapp/app.cljs, webapp/src/webapp/events/jira_templates.cljs, webapp/src/webapp/jira_templates/connections_section.cljs, webapp/src/webapp/jira_templates/create_update_form.cljs, webapp/src/webapp/jira_templates/helpers.cljs
This PR implements the backend changes necessary to support bidirectional relationships between Jira Issue Templates and Connections. Previously, connections could reference a Jira Issue Template, but there was no way to get or set associated connections directly from the template.
Also, this PR adds the ability to associate connections with Jira templates in the frontend, enabling users to select which connections a template should be applied to. This feature enhances the workflow by allowing template configurations to be connection-specific.
- Added `connection_ids` field to `JiraIssueTemplate` response to return associated connections
- Added `connection_ids` field to `JiraIssueTemplateRequest` to allow setting connections during template creation/update
- Implemented helper functions …
=> Bidirectional Association Between Jira Issue Templates and Connections

Dockerfile.dev, deploy/helm-chart/chart/gateway/templates/deployment.yaml, deploy/helm-chart/chart/gateway/templates/secret-configs.yaml, deploy/helm-chart/chart/gateway/templates/service.yaml, deploy/helm-chart/chart/gateway/values.yaml, rootfs/usr/local/bin/hoop-default-agent.sh
- Improve the default agent to connect using TLS when `TLS_CA` env is set in the gateway
- Add `tini` to run agent under pid 1
=> [helm-chart] Improve helm-chart to allow customizing service definition to work with GCP ingress

.env.sample, deploy/helm-chart/chart/gateway/templates/secret-configs.yaml, gateway/analytics/segment.go, gateway/api/openapi/types.go, gateway/api/serverinfo/serverinfo.go, gateway/appconfig/appconfig.go, webapp/resources/public/index.html, webapp/src/webapp/app.cljs, webapp/src/webapp/events.cljs, webapp/src/webapp/events/clarity.cljs, webapp/src/webapp/events/gateway_info.cljs, webapp/src/webapp/events/segment.cljs, webapp/src/webapp/events/tracking.cljs, webapp/src/webapp/shared_ui/sidebar/main.cljs
This PR supports the `do_not_track` flag from the serverinfo API, allowing complete disabling of all tracking and analytics tools when enabled.
- Added subscription for `do_not_track` flag from serverinfo API response
- Removed hardcoded tracking scripts from `index.html`
- Created a dynamic tracking initialization system that only loads scripts when tracking is allowed
- Implemented a centralized mechanism for tracking management
- **Segment**: Conditionally loads and initializes based on `do_not_track` setting
- **Clarity**: Added safe verification before calls and respects the tracking preference
- **Intercom**: Updated initialization to check tracking preferences
- **Canny**: Modified user identification to happen only when tracking is allowed
- **Sentry**: Delayed initialization …
=> Add Support for do_not_track Flag

Dockerfile.dev, Dockerfile.tools, deploy/docker-compose/Dockerfile, gateway/transport/connectionstatus/connectionstatus.go, rootfs/usr/local/bin/bq, scripts/dev/Dockerfile, webapp/package-lock.json
- [agent] Add python3.9 to agent tools to avoid printing warning when using the bq cli
- [agent] Bump agent tools to 0.0.10 containing python3.9
=> [agent] Update bq command line tool to accept project id as environment variable

webapp/package-lock.json, webapp/package.json, webapp/resources/public/index.html, webapp/src/webapp/app.cljs, webapp/src/webapp/auth/views/logout.cljs, webapp/src/webapp/events.cljs, webapp/src/webapp/events/auth.cljs, webapp/src/webapp/events/clarity.cljs, webapp/src/webapp/events/gateway_info.cljs, webapp/src/webapp/events/segment.cljs, webapp/src/webapp/events/tracking.cljs, webapp/src/webapp/onboarding/setup.cljs, webapp/src/webapp/shared_ui/sidebar/main.cljs, webapp/src/webapp/shared_ui/sidebar/navigation.cljs
This PR supports the `analytics_tracking` flag from the server info API, which allows complete disabling of all tracking and analytics tools when enabled.
- Added subscription for `analytics_tracking` flag from serverinfo API response
- Removed hardcoded tracking scripts from `index.html`
- Created a dynamic tracking initialization system that only loads scripts when tracking is allowed
- Implemented a centralized mechanism for tracking management
- **Segment**: Conditionally loads and initializes based on `analytics_tracking` setting
- **Clarity**: Added safe verification before calls and respects the tracking preference
- **Intercom**: Updated initialization to check tracking preferences
- **Canny**: Modified user identification to happen only when tracking is allowed
- **Sentry**: …
=> Analytics tracking re-implementation

gateway/api/connections/connections.go, gateway/api/connections/helpers.go, gateway/api/connections/helpers_test.go, gateway/api/connections/queries_schema.go, gateway/api/openapi/autogen/docs.go
This PR addresses several issues with database schema exploration and improves support for different database types.
- Fix schema exploration to include tables from all schemas (not just "public")
- Add support for views and materialized views in addition to tables
- Remove the `pg_table_is_visible(c.oid)` condition that was filtering out tables not in the current search_path
- Add support for views in schema listing
- Update queries to properly distinguish between tables and views
- Enhance type detection for MongoDB-specific types (NumberLong, NumberInt, NumberDecimal)
- Improve schema detection by examining multiple documents (up to 10) instead of just one
- Reorder parameters in MongoDB commands for better compatibility
- Add specific test case to verify schema "private" tables are …
=> Enhance database schema exploration functionality

.gitignore, webapp/src/webapp/connections/views/setup/events/db_events.cljs, webapp/src/webapp/connections/views/setup/events/effects.cljs, webapp/src/webapp/connections/views/setup/events/process_form.cljs, webapp/src/webapp/connections/views/setup/events/subs.cljs, webapp/src/webapp/connections/views/setup/server.cljs, webapp/src/webapp/db.cljs
Introduce an argument-based interface for command input, improving flexibility and usability.
The API expects a list, and current behavior splits the string input by space. We should let the user input a string and so giving users more power while removing the magic from the process.
=> Enhance command input with argument-based interface

gateway/models/connections.go
Check if the user groups overlap with the array access control plugin configuration instead of the contains operator.
=> [hotfix] Fix listing connections via access control

deploy/helm-chart/chart/gateway/values.yaml
A search over the Helm chart shows that the`.Values.config.notification` map is declared but not used anywhere in the templates. It can be removed to avoid confusion.
=> Remove unused notification block from Helm values

webapp/package.json, webapp/src/webapp/components/ag_grid_table.cljs
This PR fixes a critical issue where AG Grid fails to render when TSV data contains tab characters within cell values. The error "No item X in vector of length Y" occurs because tab characters are interpreted as column delimiters, creating misalignment between row length and header count.
Previous implementation with DataGridXL2 tolerated these inconsistencies, but AG Grid's stricter data structure requirements cause it to crash.
- Added a smart data normalization function that handles rows with inconsistent column counts
- Implemented intelligent empty cell removal algorithm that preserves valuable content
- Added robust error handling to prevent blank screens when data issues occur
- Simplified validation logic to attempt rendering when data can be normalized
This is a defensive …
=> Fix AG Grid rendering failure caused by tab characters in cell values

webapp/src/webapp/events/editor_plugin.cljs, webapp/src/webapp/events/jira_templates.cljs, webapp/src/webapp/jira_templates/cmdb_error.cljs, webapp/src/webapp/jira_templates/loading_jira_templates.cljs
When executing a query for a connection with a Jira template that requires CMDB data, the system would get stuck in an infinite loading state if:
1. The initial CMDB request timed out
2. The user clicked "Try Again"
3. The retry was successful
This created a poor user experience as users were stuck in a loading screen with no way to proceed, even though the data was successfully retrieved.
This PR enhances the error handling for Jira CMDB requests by:
1. Providing clearer messaging about CMDB loading and errors
2. Implementing a complete retry flow that properly handles both success and failure cases
3. Maintaining context across retry attempts to ensure the user can continue their workflow
- Updated text in `loading_jira_templates.cljs` to clarify that CMDB data is being loaded from Jira …
=> Improve Jira CMDB Error Handling and Fix Retry Loop

gateway/api/integrations/issuetemplates.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/api/server.go, gateway/jira/assetsapi.go, gateway/jira/types.go, webapp/src/webapp/components/forms.cljs, webapp/src/webapp/components/paginated_dropdown.cljs, webapp/src/webapp/connections/views/connection_settings_modal.cljs, webapp/src/webapp/connections/views/setup/events/db_events.cljs, webapp/src/webapp/connections/views/setup/events/process_form.cljs, webapp/src/webapp/events/connections.cljs, webapp/src/webapp/events/jira_templates.cljs, webapp/src/webapp/jira_templates/create_update_form.cljs, webapp/src/webapp/jira_templates/prompt_form.cljs
CMDB fields were loading all data simultaneously, causing significant performance issues when loading forms for clients with large volumes of data (15,000+ items).
We implemented a paginated loading system with real-time search for CMDB selection dropdowns in the Jira templates form.
1. Open a Jira template with CMDB types
2. Verify that the dropdown initially loads only the first page
3. Use search to filter values
4. Navigate between pages and confirm that data loads correctly
5. Select a value and verify that the form recognizes the selection
- Breaking Change: remove route GET /api/integrations/jira/issuetemplates/123/objecttype-values
- Introduce new route to list object values from Jira Assets API
- Add default timeout (50s) when performing request to asset objects api
- Remove …
=> Jira: Implementation of Pagination for CMDB Data

webapp/package.json, webapp/src/webapp/webclient/components/connections_list.cljs, webapp/src/webapp/webclient/components/database_schema.cljs
This PR fixes a critical bug in the database schema component where the schema would fail to load when switching between already selected connections, and includes several UI and code quality improvements.
**Issue:** When switching between database connections without removing the current selection first, the database schema would fail to load on the third connection switch, requiring users to manually close and reopen the schema panel.
**Root Cause:** Race condition in the component lifecycle management where the `loading-started` flag wasn't properly reset when the global schema was cleared via `:database-schema->clear-schema` event.
- Fixed race condition in `component-did-update` lifecycle method
- Added detection for global schema clearing when switching connections
- Implemented …
=> Fix database schema loading on connection switching + UI improvements

webapp/package.json, webapp/src/webapp/events/gateway_info.cljs, webapp/src/webapp/settings/license/panel.cljs, webapp/src/webapp/shared_ui/sidebar/components/profile.cljs, webapp/src/webapp/webclient/components/connections_list.cljs, webapp/src/webapp/webclient/components/database_schema.cljs, webapp/src/webapp/webclient/log_area/logs.cljs, webapp/src/webapp/webclient/panel.cljs
This PR implements a license expiration warning system that displays alerts to admin users when their enterprise license is approaching expiration (3 months or less remaining).
- **Added subscription** `gateway->should-show-license-expiration-warning` in `gateway_info.cljs`
- Checks if user is admin
- Validates enterprise license status
- Calculates if expiration is within 3 months (90 days)
- **License Management Page** (`settings/license/panel.cljs`)
- Added yellow warning callout above license information table
- Uses `AlertCircle` icon with warning text
- **Terminal Sidebar** (`webclient/components/connections_list.cljs`)
- Added fixed warning banner at bottom of connections sidebar
- Includes "Go to license page" navigation link
- Implemented proper layout with `flex-1 overflow-auto` …
=> Add License Expiration Warning for Admin Users

gateway/api/runbooks/runbooks.go
It prevents nil pointer exception when a runbook file doesn't exists when fetching from the git repository.
=> [bugfix] Fix nil pointer when runbook file does not exists

agent/secretsmanager/aws.go
Improve logging to not leak sensitive AWS resource information when secrets manager is enabled.
=> agent: make debug level to log aws response instead of printing the body response

common/proto/const.go, common/proto/types.go, gateway/api/connections/connections.go, gateway/api/connections/helpers.go, gateway/api/connections/helpers_test.go, gateway/api/connections/queries_schema.go, webapp/package.json, webapp/src/webapp/connections/views/setup/additional_configuration.cljs, webapp/src/webapp/connections/views/setup/connection_update_form.cljs, webapp/src/webapp/connections/views/setup/events/process_form.cljs, webapp/src/webapp/connections/views/setup/server.cljs, webapp/src/webapp/events/database_schema.cljs, webapp/src/webapp/events/editor_plugin.cljs, webapp/src/webapp/webclient/components/connections_list.cljs, webapp/src/webapp/webclient/components/database_schema.cljs, webapp/src/webapp/webclient/panel.cljs
This PR implements comprehensive support for **AWS CloudWatch** as a new connection type in Hoop. The implementation allows users to connect to CloudWatch, browse log groups, select them dynamically, and execute queries with the selected log group automatically injected as an environment variable.
- **Added CloudWatch connection type constant** in `common/proto/const.go`
- **Enhanced connection type mapping** in `common/proto/types.go` to support `custom/cloudwatch`
- **Implemented CloudWatch schema queries** in `gateway/api/connections/queries_schema.go`
- Added `getCloudWatchTablesQuery()` using `aws logs describe-log-groups --output json`
- No column queries needed (CloudWatch logs don't have fixed schema)
- **Created CloudWatch parser** in `gateway/api/connections/helpers.go`
- …
=> Implement AWS CloudWatch connection type with log group schema browsing

webapp/package.json, webapp/src/webapp/audit/views/session_details.cljs
Fixed a bug in the session details view where user group access checking was using an incorrect data path. The code was trying to access user groups via `(-> user :data :groups)` when it should be accessing them directly via `(-> user :groups)`. This fix ensures that session review permissions are properly validated based on the user's group membership.
- Fixed user group access path in session details view from `(-> user :data :groups)` to `(-> user :groups)`
- Updated package.json version to 1.47.7
- Corrected session review permission validation logic
- **Browser(s)**: Chrome, Firefox
No UI changes - this is a backend logic fix.
This fix addresses an issue where users who should have been able to review sessions based on their group membership were unable to do so due …
=> Fix: Correct user group access path in session details view

common/proto/const.go, gateway/api/connections/connections.go, gateway/api/connections/helpers.go, gateway/clientexec/clientexec.go, gateway/transport/client.go, webapp/package-lock.json
- Add override to `bash` for cloudwatch and dynamodb connection types
=> Add command override to plain exec executions

webapp/package.json, webapp/src/webapp/connections/constants.cljs, webapp/src/webapp/events/editor_plugin.cljs, webapp/src/webapp/features/runbooks/events.cljs, webapp/src/webapp/features/runbooks/main.cljs, webapp/src/webapp/reviews/panel.cljs, webapp/src/webapp/webclient/panel.cljs, webapp/src/webapp/webclient/runbooks/list.cljs
This PR fixes two critical issues in the webapp:
1. **Runbooks path normalization**: Ensures runbook paths are stored without leading slashes (e.g., `ops/test` instead of `/ops/test`)
2. **Reviews approver parameter fix**: Resolves an issue where `review.approver` was being sent as empty after reviewing a review
- Added `normalize-path` function in `src/webapp/features/runbooks/events.cljs`
- Implemented path normalization in `:runbooks/add-path-to-connection` event
- Ensures paths are stored without leading slashes (e.g., `ops/test` instead of `/ops/test`)
- Updated placeholder text in runbook form to show the expected format
- Fixed initialization of `review-user` atom in `src/webapp/reviews/panel.cljs`
- Updated initial dispatch to include user parameter: `[:reviews-plugin->get-reviews …
=> Fix: Normalize runbooks paths and fix reviews approver parameter

Dockerfile.tools, scripts/dev/Dockerfile
The apt repository for Postgres changed to apt-archive for Ubuntu Focal distribution.
=> fix: add apt-archive to postgres client 15.

webapp/src/webapp/connections/views/hoop_cli_modal.cljs
brew tap brew doesn't work
```
brew tap brew https://github.com/hoophq/brew
Error: Invalid tap name: 'brew'
```
Fixes #
- [X ] 🐛 Bug fix (non-breaking change which fixes an issue)
- 
- 
- 
Tested on Mac 15.5
- **Browser(s)**: 
- **OS**:
---
=> [fix] fix brew tap as it returns invalid tap name on mac

webapp/package.json, webapp/src/webapp/http/request.cljs, webapp/src/webapp/shared_ui/sidebar/navigation.cljs
This PR fixes an issue where the HTTP request handler would fail when trying to parse JSON from responses that have no body content (e.g., 204 No Content, 205 Reset Content, 304 Not Modified). The solution automatically detects empty responses and handles them appropriately without throwing parsing errors.
- Modified `parse-response` function to check if response body is empty before attempting JSON parsing
- Used response cloning to safely check content without consuming the original stream
- Removed hard-coded status code list in favor of automatic empty body detection
- Returns `nil` for successful responses with no content instead of throwing parsing errors
- **Browser(s)**: Chrome, Firefox, Safari
=> Fix: Handle HTTP responses without body content gracefully

webapp/package.json, webapp/src/webapp/events/license.cljs
Added error handling for JSON parsing in the license update event to provide better user feedback when invalid JSON is submitted.
- Added try-catch block around JSON.parse in `:license->update-license-key` event
- Implemented error snackbar notification when JSON parsing fails
- Provided user-friendly error message with technical details for debugging
- **Browser(s)**: Chrome, Firefox, Safari
- **OS**: macOS, Windows, Linux
=> fix: Add JSON parse error handling in license update event

gateway/api/connections/connections.go
Exclude 'rdsadmin' from the list of database endpoint when it is a PostgreSQL connection
=> Exclude 'rdsadmin' from the list of database endpoint when it is a PostgreSQL connection

webapp/package.json, webapp/src/webapp/connections/views/setup/connection_update_form.cljs, webapp/src/webapp/connections/views/setup/events/db_events.cljs, webapp/src/webapp/connections/views/setup/events/process_form.cljs, webapp/src/webapp/connections/views/setup/events/subs.cljs, webapp/src/webapp/connections/views/setup/server.cljs
This PR adds a Resource Subtype Override feature that allows custom connections to specify their actual resource type (DynamoDB or CloudWatch) while maintaining the flexibility of custom connection configuration. This enables users to get optimal settings and features for specific resource types while still using the custom connection workflow.
- Added Resource Subtype Override select component for custom connections in edit mode
- Implemented event handlers and subscriptions for managing subtype override state
- Updated form processing logic to use override value as actual subtype when specified
- Added proper loading/saving logic to detect and preserve existing override configurations
- Integrated with existing forms component system for consistent UI styling
- Added Beta badge to …
=> Add Resource Subtype Override for Custom Connections

.github/workflows/release.yml, Dockerfile, Dockerfile.dev, Dockerfile.tools, scripts/dev/Dockerfile
- Add multi image architecture (amd64 and arm64)
- `hoophq/hoop` - Gateway
- `hoophq/hoopdev`  - Agent
- Agent: update python3.9 to python3.12
- Agent: update aws cli to 2.28.6
- Agent: update google cli to 533.0.0-0
- Agent: update node to 22.18 (LTS)
- Agent: add redis-cli tool
- Agent: update kubectl cli to 1.29.15
- Agent: add legacy mongo client and update mongosh to 2.5.6
- Agent: update postgres client to 16.9-0ubuntu0.24.04.1 (main ubuntu repo)
- Agent: update default mysql client to 1.1.0build1 (main ubuntu repo)
- Agent: update oracle clients to 23.9
- Agent: update python3 libs boto3 to 1.40.6 and requests to 2.32.4
- Agent: add compatibility with libaio by creating a symlink with newest libaio package (libaio1t64)
- Agent: removed clojure and jre
=> Update base images with Ubuntu 24.04 LTS (Noble Numbat)

gateway/api/connections/connections.go, gateway/api/connections/helpers.go, gateway/api/openapi/autogen/docs.go, gateway/api/openapi/types.go, gateway/api/server.go
Added a new Test Connection endpoint that allows users to validate database connections by performing a simple ping test. This feature helps users verify their connection configuration before using it in production environments.
Furthermore, fixes the OracleDB library path to version 23.9 to match the docker file.
- Added `TestConnection` endpoint at `/connections/{nameOrID}/test` that validates database connections
- Implemented connection testing logic for multiple database types (PostgreSQL, MySQL, MSSQL, OracleDB, MongoDB, DynamoDB, CloudWatch)
- Added `ConnectionTestResponse` type to OpenAPI schema with proper documentation
- Updated OracleDB library path from version 19.24 to 23.9 in connection defaults
- Added proper error handling and logging for connection test failures
- …
=> feat: add test connection endpoint

webapp/src/webapp/app.cljs
Some users are experiencing a login loop caused by the deprecated request to plugins for getting the editor info.
=> Remove plugin dispatch in editor plugin panel

webapp/src/webapp/audit/views/session_data_video.cljs, webapp/src/webapp/shared_ui/cmdk/command_palette_pages.cljs
This PR hides the visible scrollbar in the video session view to prevent unwanted screen shaking.
It also fixes an error that occurred when a database connection was previously selected and the user tried to switch connections using Cmd+K.
- Updated the styles from `session_data_video.cljs` component to hide y overflows in the Tab content.
- Clear `selected-database` localStorage when switch connection using cmd+k.
1. Video session
- Go to the session page and select one item that has a video;
- Force one overflow by adding some extra height to the video wrapper;
- Confirm video playback and layout remain stable.
2. Connection switching
- Select a database for connection A in the connections page, then switch to connection B using Cmd+K. 
- Confirm that doesn't shows an error related to …
=> fix: Prevent showing scrollbar in video session view

gateway/api/connections/helpers.go, rootfs/app/migrations/000046_remove_oracle_ld.up.sql
Refactored OracleDB connection logic by removing the `LD_LIBRARY_PATH` environment variable from the connection setup.
There were some changes made on `libhoop` to use the `LD_LIBRARY_PATH` from user environment.
- Removed LD_LIBRARY_PATH from OracleDB connection in `gateway/api/connections/helpers.go`
- Ensured OracleDB connection uses only required environment variables and command arguments
=> fix: OracleDB connection issues because LD_LIBRARY_PATH

webapp/src/webapp/audit/views/audit_filters.cljs, webapp/src/webapp/reviews/panel.cljs
This PR fixes a state management issue where filter search results were persisting across popover interactions, causing confusing UX. Users would see previous search results when reopening filters instead of the full list. The solution required migrating from Headless UI to Radix UI to enable proper state reset functionality.
- **Fixed state persistence bug**: Added `on-click` handlers to reset search state when opening filter popovers
- **Migrated to Radix UI**: Replaced Headless UI Popovers with Radix UI to enable `on-click` functionality on triggers
- **State reset implementation**: Clear `searched-users`, `searched-connections`, and `searched-criteria-*` atoms on popover open
- **Improved UX consistency**: Users now always see the complete filter options when opening popovers
- …
=> [FIX] Reset filter search state when opening popovers
